FUSETOOLS2-2077: Create UI test for Specific Camel JBang version sett…
camel-tooling/camel-lsp-client-vscode pull request #1369
Opened 2023-06-05 23:15 UTC by pospisilf

…ings

# Pull Request informations

## Rebase & Merge default requirements

1. Green build for main branch
2. Wait 24 hours after PR creation
3. Green job for PR
4. Approved PR

## PR labels default process

- READY_FOR_REVIEW  &rightarrow;  REVIEW_DONE  &rightarrow;  READY_FOR_MERGE

## Tests

- [ ] Are there **Unit tests**?
- [ ] Are there **Integration tests**?
- [ ] Do we need a new **UI test**?

## PR workflow progress

1. [ ] Tagged with relevant **PR labels**
2. [ ] Green **job for PR**
3. [ ] PR was created more than **24 hours ago** or **All committers approved** it
4. [ ] Green **main** branch build

2023-06-23 08:03 UTC, djelinek requested changes

2023-06-28 06:50 UTC, pospisilf commented on src/ui-test/tests/jbang_user_preference.test.ts
> +                await DefaultWait.sleep(10000);
unstable if no static wait here - do not know why yet

2023-06-30 08:38 UTC, pospisilf commented on src/ui-test/tests/jbang_user_preference.test.ts
> +                await DefaultWait.sleep(10000);
huge thanks to @djelinek for finding solution

2023-06-30 10:36 UTC, djelinek requested changes

2023-06-30 10:36 UTC, djelinek commented on src/ui-test/tests/jbang_user_preference.test.ts
> +        fs.remove(path.resolve(RESOURCES, filename), (err: any) => {
`remove` is async.. you need to modify method to return Promise and use await or use `fs.removeSync` instead

2023-06-30 10:36 UTC, djelinek commented on src/ui-test/tests/jbang_user_preference.test.ts
> +            terminalView = await new BottomBarPanel().openTerminalView();
terminal cleanup could be moved to `afterEach`

2023-06-30 10:36 UTC, djelinek commented on src/ui-test/tests/jbang_user_preference.test.ts
> +            await new Workbench().executeCommand('Camel: Create a Camel Route using XML DSL');
init and wait for file is created could be moved to method and reused in both tests

2023-06-30 10:36 UTC, djelinek commented on src/ui-test/tests/jbang_user_preference.test.ts
> +describe('JBang user preference version set test', function () {
I would maybe change the filename from `jbang_user_preference.test.ts` to `camel_jbang_version.test.ts` it seems to me more precise and it goes hand to hand with already existing `camel_catalog_version.test.ts` WDYT?

2023-06-30 12:48 UTC, djelinek approved these changes

2023-07-04 15:17 UTC, merged