FUSETOOLS2-1990: Create UI Tests for code navigation to Camel Contexts and Routes
camel-tooling/camel-lsp-client-vscode pull request #1422
Opened 2023-07-21 12:09 UTC by pospisilf

# Pull Request informations

## Rebase & Merge default requirements

1. Green build for main branch
2. Wait 24 hours after PR creation
3. Green job for PR
4. Approved PR

## PR labels default process

- READY_FOR_REVIEW  &rightarrow;  REVIEW_DONE  &rightarrow;  READY_FOR_MERGE

## Tests

- [ ] Are there **Unit tests**?
- [ ] Are there **Integration tests**?
- [ ] Do we need a new **UI test**?

## PR workflow progress

1. [ ] Tagged with relevant **PR labels**
2. [ ] Green **job for PR**
3. [ ] PR was created more than **24 hours ago** or **All committers approved** it
4. [ ] Green **main** branch build

2023-07-21 12:11 UTC, pospisilf commented
Blocked by https://github.com/camel-tooling/camel-lsp-client-vscode/pull/1418

2023-07-21 12:42 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +        // All vailable symbols in 'camel-route.xml' with line of occurence.
type: `available`

2023-07-21 12:42 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +        const XML_av_symobls = [
typo: `symbols`

2023-07-21 12:42 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +        const JAVA_av_symobls = [
typo: `symbols`

2023-07-21 12:42 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +        await section.isExpanded(); // roztahnout
czech comments 😄

2023-07-21 12:42 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +
redundant empty line

2023-07-21 12:42 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +            it('all symbol proposals are avaialble', async function () {
typo: `available`

2023-07-21 12:42 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +            it('all symbol proposals are avaialble', async function () {
typo: `available`

2023-07-21 12:42 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +            it('all symbol proposals are avaialble', async function () {
typo: `available`

2023-07-21 12:42 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +            it('all symbol proposals are avaialble', async function () {
typo: `available`

2023-07-21 12:42 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +import path = require("path");
better to use `import * as path from 'path'`

2023-07-24 08:36 UTC, pospisilf commented on src/ui-test/tests/code.navigation.test.ts
> +        await section.isExpanded(); // roztahnout
labels: DRAFT 😅

2023-07-25 11:17 UTC, pospisilf commented on src/ui-test/tests/code.navigation.test.ts
> +                await allSymbolsAreAvailableInOutlineSideBar(JAVA_av_symbols);
wrong test called

2023-08-01 10:09 UTC, djelinek requested changes

2023-08-01 10:09 UTC, djelinek commented on src/ui-test/tests/code.navigation.test.ts
> +        describe('Quickpick \'Go to Symbol in Editor\' navigation', function () {
is this different test or we can unify naming of this and following describe with Java DSL ones?

2023-08-02 14:36 UTC, merged