Adds Create Camel project to the welcome screen
camel-tooling/camel-lsp-client-vscode pull request #1994
Opened 2024-10-31 13:41 UTC by hdamarcelo

Adds Create Camel projecy to the welcome screen
    
- Rename NewCamelProjectCommand class to reflect its abstract nature.
- Create a 'generic' NewCamelProjectCommand that asks the user to select a runtime. Register the command with 'enablement = false' so that its does not show in the command palette.
- Refactor other classes with the new project structure.

![welcome](https://github.com/user-attachments/assets/36855d4a-a8b1-41f8-a57e-02219a90df43)

2024-10-31 20:51 UTC, djelinek commented on package.json
> +
empty line

2024-10-31 20:51 UTC, djelinek commented on src/commands/NewCamelQuarkusProjectCommand.ts
> +	async getRuntime(): Promise<string> {
is this really needs to be an `async` function?

2024-10-31 20:51 UTC, djelinek commented on src/commands/NewCamelSpringBootProjectCommand.ts
> +	async getRuntime(): Promise<string> {
is this really needs to be an `async` function?

2024-10-31 20:51 UTC, djelinek commented on src/ui-test/tests/commands.projects.test.ts
> +describe.only('Create a Camel Project using command', function () {
remove `only` when code is ready

2024-10-31 20:51 UTC, djelinek commented on Changelog.md
empty line

2024-11-12 16:30 UTC, apupier requested changes
tests are failing on Windows

2024-11-25 02:35 UTC, hdamarcelo commented
> tests are failing on Windows

After some testing using a VM I was able to reproduce the error we can see in the test pipeline but unfortnutatly not solve it (the error is the same in [PR1952](https://github.com/camel-tooling/camel-lsp-client-vscode/pull/1952))

Tests I made while trying to reproduce the error:

1. Execute `npm run ui-test` inside vscode integrated terminal: The issue is that after the command execution (after the task that runs `jbang camel export` completes) no pom.xml file is created and because of that the test assertion fails. During the test execution I can see the following error in the terminal among other warning messages (they do not appear on linux)
>ERR: [File Watcher (node.js)] Failed to watch c:\<path-to-project>\camel-lsp-client-vscode\src\ui-test\resources\create-camel-project-workspace\.vscode for changes using fs.watch() (Error: EPERM: operation not permitted, watch, undefined)", source: vscode-file://vscode-app/c:/<path-to-user-folder>/AppData/Local/Temp/test-resources/VSCode-win32-x64-archive/resources/app/out/vs/workbench/workbench.desktop.main.js (35)
  
2. Execute `npm run ui-test` outside vscode: Same result as 1
3. Execute `npm run ui-test` in windows bash: Same result as 1
4. Execute `npm run ui-test` in windows powershell: Same result as 1
5. Execute `npm run ui-test` changing camel.jbang.version to 4.8.0: Same result as 1
6. Running the command "Create a Camel Project" after running the extension (hitting F5): `jbang camel export` fails due to a simultaneous lock in a NTUSER.DAT file inside .camel-jabng folder (file is deleted after command execution)
7. Running the command "Create a Camel Project" after running the extension (hitting F5) as administrator: Same result as 6
8. Running the command "Create a Camel Project" after installing the built vsix (without running the project in another vscode instance): pom.xml file is created as expected

While adding pauses in each step of the ui-test execution it seems to me that the camel jbang process ends early and does not create the pom.xml file during the test suite execution.

I also tried executing camel jbang via a child process intead of using vscode's ShellExecution method but that also did not work.

2024-12-04 14:20 UTC, apupier requested changes
side-tracked and wasn't able to test it locally yet but would like to provide the initial feedback

2024-12-05 09:36 UTC, apupier requested changes

2024-12-05 09:36 UTC, apupier commented on src/commands/AbstractNewCamelProjectCommand.ts
> +	abstract getRuntime(): Promise<string|undefined>;
I think we need to decalre it as async to have a better typing and ensure that await is called.
For instance, in camel.project.command.test.ts it is not. It is causing the title of the test to be incorrect `Should validate Create a Camel Project command GAV validation of [object Promise]`, see https://github.com/camel-tooling/camel-lsp-client-vscode/actions/runs/12173733325/job/33963279530?pr=1994#step:13:123

2024-12-05 18:26 UTC, apupier commented on src/test/suite/camel.project.command.test.ts
> +describe.only('Should validate Create a Camel Project command', function () {
do not forget to remove the .only

2024-12-09 09:08 UTC, apupier approved these changes

2024-12-09 13:16 UTC, djelinek approved these changes

2024-12-09 16:16 UTC, merged